const AppointmentsTypes = {
    GET_ALL_APPOINTMENTS: "GET_ALL_APPOINTMENTS",
    ADD_USER_APPOINTMENTS: "ADD_USER_APPOINTMENTS",
    SET_FILTERED_APPOINTMENTS: "SET_FILTERED_APPOINTMENTS",

    UPDATE_BALANCE: "UPDATE_BALANCE",
    UPDATE_COUNTS: "UPDATE_COUNTS"
};

export default AppointmentsTypes;