const TransactionsTypes = {
    PREPARE_TRANSACTION_INFO: "PREPARE_TRANSACTION_INFO",
    SAVE_TRANSACTION: "SAVE_TRANSACTION",
    GET_PREVIOUS_TRANSACTIONS: "GET_PREVIOUS_TRANSACTIONS",

    UPDATE_PREPARED_TRANSACTION_INFO_BALANCE: "UPDATE_PREPARED_TRANSACTION_INFO_BALANCE",
    UPDATE_PREPARED_TRANSACTION_INFO_COUNTS: "UPDATE_PREPARED_TRANSACTION_INFO_COUNTS"
}

export default TransactionsTypes;