const MedicalScanTypes = {
    ADD_SCAN_RECORD: "ADD_SCAN_RECORD",
    DELETE_SCAN_RECORD: "DELETE_SCAN_RECORD",

    UPDATE_SCAN_LIST_FIELD: "UPDATE_SCAN_LIST_FIELD",
    UPDATE_SCAN_MODALITY: "UPDATE_SCAN_MODALITY",

    UPDATE_ORIGINAL_SCAN_AMOUNT_FIELD: "UPDATE_ORIGINAL_SCAN_AMOUNT_FIELD",
    UPDATE_ORIGINAL_SCAN_DISCOUNT_FIELD: "UPDATE_ORIGINAL_SCAN_DISCOUNT_FIELD",

    UPDATE_RUNNING_SCAN_AMOUNT_FIELD: "UPDATE_RUNNING_SCAN_AMOUNT_FIELD",
    UPDATE_RUNNING_SCAN_DISCOUNT_FIELD: "UPDATE_RUNNING_SCAN_DISCOUNT_FIELD",

    UPDATE_CURRENT_SCAN_MODALITY: "UPDATE_CURRENT_SCAN_MODALITY",
    UPDATE_CURRENT_SCAN_AMOUNT_FIELD: "UPDATE_CURRENT_SCAN_AMOUNT_FIELD",
    UPDATE_CURRENT_SCAN_DISCOUNT_FIELD: "UPDATE_CURRENT_SCAN_DISCOUNT_FIELD"
};

export default MedicalScanTypes;